project:
  type: website
  preview:
    port: 4200
    browser: true
    watch-inputs: true

website:
  title: "SynthFair"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles_modern_teal.css
    toc: true
    toc-depth: 3
    toc-location: left
    number-sections: false
    code-fold: false
    smooth-scroll: true
    fig-align: center
    fig-cap-location: bottom
    link-external-newwindow: true
    html-math-method: katex



